# Generated by Django 2.2.7 on 2020-01-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_businessprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='email',
        ),
    ]
