# Generated by Django 2.2.7 on 2020-01-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_address'),
        ('user_management', '0003_userpreference_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=60)),
                ('service', models.CharField(choices=[('venue-only', 'Venue Facility'), ('event-only', 'Event Organizer'), ('venue-event', 'Both')], default='venue-event', max_length=20)),
                ('contact_person', models.CharField(max_length=40)),
                ('contact_mobile', models.CharField(max_length=11)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
