# Generated by Django 2.2.7 on 2020-02-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dh_test', '0002_androidtestusers_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AndroidTestUsers',
            new_name='AndroidTestUser',
        ),
    ]
