# Generated by Django 2.2.7 on 2020-01-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event/banner/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('open_gallery', models.BooleanField(blank=True, default=True)),
                ('seat_range', models.IntegerField(blank=True, default=-1)),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('organizer', models.CharField(max_length=60)),
                ('instruction', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.TextField()),
                ('capacity', models.IntegerField()),
                ('contact_person', models.CharField(max_length=40)),
                ('contact_mobile', models.CharField(max_length=11)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.Event')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Preference')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
