# Generated by Django 2.2.7 on 2020-01-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_auto_20200112_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='preference',
            new_name='preferences',
        ),
    ]
