# Generated by Django 2.2.7 on 2020-01-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_auto_20200112_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seat_range',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
