# Generated by Django 2.2.7 on 2020-01-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_auto_20200113_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='title',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
