# Generated by Django 2.2.7 on 2020-01-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0006_auto_20200113_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='title',
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
