# Generated by Django 2.2.7 on 2020-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0007_auto_20200113_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='contact_mobile',
            field=models.CharField(max_length=20),
        ),
    ]
