# Generated by Django 2.2.7 on 2020-01-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0008_auto_20200115_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='preferences',
            field=models.ManyToManyField(through='event_management.EventPreference', to='settings.Preference'),
        ),
    ]
